#!/usr/bin/env python3
"""Session Brief — the generated session-start read.

Replaces "read docs/STATE.md first" as an agent's opening move.

THE PRINCIPLE: derive live state from its source of truth AT READ TIME; hand-write
only decisions and intent.

Hand-maintained mirrors of live state rot, silently and measurably — a doc that
says "currently deployed: v4.2" is wrong the moment it isn't, and an agent will
cite it with total confidence. So this brief DERIVES what it can (git, CI, doc
freshness) and POINTS at the small hand-written surfaces that remain
authoritative for intent (decisions, NOW/NEXT).

Every absence is stated, never silent: a seat without `gh` gets a printed line
saying so, not a section that quietly disappears. An agent must be able to tell
"there are no open PRs" from "I couldn't look."

Usage:
  python scripts/session_brief.py
  python scripts/session_brief.py --decisions 12
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import subprocess
import sys
from pathlib import Path

# --- CONFIGURATION — edit for your repo ------------------------------------

DEFAULT_BRANCH_CANDIDATES = ("origin/main", "origin/master", "origin/maintenance")
MIGRATIONS_DIR_MARKER = "alembic/versions"

#: TTL in days per STATE.md section class. Exceeding it prints a STALE verdict.
TTL_DAYS = {"NOW": 3, "NEXT": 3, "ACTIVE WORKSTREAMS": 7}

# ---------------------------------------------------------------------------

REPO = Path(__file__).resolve().parent.parent
DECISIONS_MD = REPO / "docs/DECISIONS.md"
STATE_MD = REPO / "docs/STATE.md"
HANDOFFS_DIR = REPO / "docs/handoffs"

DECISION_LINE_RE = re.compile(r"^- \*\*(\d{4}-\d{2}-\d{2})\*\* — (.+)$")
# Match the heading FIRST, then look for the date inside its remainder. Do not
# fold the date into the heading pattern: a heading with a malformed or missing
# stamp would then fail to match at all and vanish from the report — reading as
# "no such section" rather than "that section is unstamped". Silent invisibility
# is the exact failure this whole framework exists to prevent.
SECTION_RE = re.compile(r"^## ([A-Z][A-Z /]+?)(?:\s*—\s*(.*))?\s*$")
AS_OF_RE = re.compile(r"as-of:\s*(\d{4}-\d{2}-\d{2})")


def git(*args: str) -> str | None:
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), *args],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def gh(*args: str) -> str | None:
    if not shutil.which("gh"):
        return None
    try:
        return subprocess.run(
            ["gh", *args], capture_output=True, text=True, check=True, timeout=20,
            cwd=str(REPO),
        ).stdout.strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None


def rule(title: str) -> None:
    print(f"\n{'─' * 72}\n{title}\n{'─' * 72}")


def days_since(datestr: str, today: dt.date) -> int:
    return (today - dt.date.fromisoformat(datestr)).days


def section_stamps(text: str) -> list[tuple[str, str | None]]:
    out = []
    for line in text.splitlines():
        m = SECTION_RE.match(line.strip())
        if not m:
            continue
        remainder = m.group(2) or ""
        d = AS_OF_RE.search(remainder)
        out.append((m.group(1).strip(), d.group(1) if d else None))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--decisions", type=int, default=6,
                    help="how many recent decisions to print (default 6)")
    args = ap.parse_args()

    today = dt.datetime.now(dt.timezone.utc).date()
    print(f"SESSION BRIEF — {today.isoformat()} (UTC), generated by scripts/session_brief.py")

    # -- repository truth (always available: this is a checkout) -------------
    rule("REPOSITORY")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    print(f"  branch          {branch or '(unknown)'}")

    default_ref = next(
        (r for r in DEFAULT_BRANCH_CANDIDATES
         if git("rev-parse", "--verify", "--quiet", r) is not None),
        None,
    )
    if default_ref:
        tip = git("log", "-1", "--format=%h %ad %s", "--date=short", default_ref)
        print(f"  {default_ref:<15} {tip}")
        ahead_behind = git("rev-list", "--left-right", "--count", f"{default_ref}...HEAD")
        if ahead_behind:
            behind, ahead = ahead_behind.split()
            print(f"  vs default      {ahead} ahead · {behind} behind")
    else:
        print("  default branch  NOT FOUND — no origin/main|master|maintenance")

    dirty = git("status", "--porcelain")
    if dirty is None:
        print("  working tree    UNKNOWN (git unavailable)")
    elif dirty:
        n = len(dirty.splitlines())
        print(f"  working tree    ⚠ DIRTY — {n} uncommitted path(s)")
    else:
        print("  working tree    clean")

    migrations = sorted(
        p for p in REPO.glob(f"**/{MIGRATIONS_DIR_MARKER}/*.py")
        if p.name != "__init__.py"
    )
    if migrations:
        print(f"  migration head  {migrations[-1].name}  ({len(migrations)} total)")

    # -- GitHub truth (optional; absence is stated) --------------------------
    rule("GITHUB")
    prs = gh("pr", "list", "--state", "open", "--limit", "20",
             "--json", "number,title,isDraft",
             "--template",
             '{{range .}}  #{{.number}}{{if .isDraft}} (draft){{end}} {{.title}}\n{{end}}')
    if prs is None:
        print("  gh CLI unavailable or not authenticated — open PRs NOT CHECKED.")
        print("  (This is an absence, not an all-clear.)")
    elif not prs.strip():
        print("  no open PRs")
    else:
        print(prs.rstrip())

    # -- decisions (hand-written, authoritative for intent) ------------------
    rule(f"RECENT DECISIONS (newest {args.decisions})")
    if not DECISIONS_MD.exists():
        print(f"  {DECISIONS_MD.relative_to(REPO)} MISSING")
    else:
        shown = 0
        for line in DECISIONS_MD.read_text(encoding="utf-8").splitlines():
            m = DECISION_LINE_RE.match(line)
            if not m:
                continue
            date, rest = m.groups()
            headline = re.sub(r"\*\*(.+?)\*\*", r"\1", rest)
            headline = re.sub(r"\s+", " ", headline).strip()
            if len(headline) > 150:
                headline = headline[:147] + "..."
            age = days_since(date, today)
            print(f"  {date} ({age:>3}d)  {headline}")
            shown += 1
            if shown >= args.decisions:
                break
        if shown == 0:
            print("  no entries yet — start with your next real decision.")
        print(f"\n  full log: {DECISIONS_MD.relative_to(REPO)}")

    # -- state freshness (derived verdict on a hand-written file) ------------
    rule("STATE FRESHNESS")
    if not STATE_MD.exists():
        print(f"  {STATE_MD.relative_to(REPO)} MISSING")
    else:
        text = STATE_MD.read_text(encoding="utf-8")
        stamps = section_stamps(text)
        if not stamps:
            print("  no `## SECTION — as-of: YYYY-MM-DD` headings found.")
        for name, stamp in stamps:
            ttl = next((v for k, v in TTL_DAYS.items() if name.startswith(k)), None)
            if ttl is None:
                continue
            if stamp is None:
                print(f"  {name:<20} ⚠ NO as-of STAMP (TTL {ttl}d)")
                continue
            age = days_since(stamp, today)
            verdict = "STALE" if age > ttl else "ok"
            mark = "⚠" if verdict == "STALE" else " "
            print(f"  {name:<20} {mark} {verdict:<5} as-of {stamp} ({age}d, TTL {ttl}d)")

        size_kb = len(text.encode("utf-8")) / 1024
        longest = max((len(l) for l in text.splitlines()), default=0)
        print(f"  size            {size_kb:.1f} KB · longest line {longest} chars")

    # -- newest handoffs -----------------------------------------------------
    rule("NEWEST HANDOFFS")
    if not HANDOFFS_DIR.exists():
        print(f"  {HANDOFFS_DIR.relative_to(REPO)} MISSING")
    else:
        files = sorted(
            (p for p in HANDOFFS_DIR.glob("*.md")
             if p.name not in {"INDEX.md", "TEMPLATE.md"}),
            reverse=True,
        )[:5]
        if not files:
            print("  none yet")
        for p in files:
            print(f"  {p.relative_to(REPO)}")

    # -- what this brief cannot know ----------------------------------------
    rule("NOT COVERED BY THIS BRIEF")
    print("  · Deployed revision and live configuration — verify on the host.")
    print("  · Anything in docs/archive/ — read-only, never current.")
    print(f"  · Intent: open {STATE_MD.relative_to(REPO)} §NOW and §NEXT before starting.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
