#!/usr/bin/env python3
"""Session Brief — generated truth at the start of an agent session.

Derive what can be derived (git, GitHub/CI, freshness) and point at the small
hand-written surfaces that remain authoritative for intent.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from state_contract import all_freshness

DEFAULT_BRANCH_CANDIDATES = ("origin/main", "origin/master", "origin/maintenance")
MIGRATIONS_DIR_MARKER = "alembic/versions"
SECTION_TTLS = {"NOW": 3, "NEXT": 3}
WORKSTREAM_TTL = 7

REPO = Path(__file__).resolve().parent.parent
DECISIONS_MD = REPO / "docs/DECISIONS.md"
STATE_MD = REPO / "docs/STATE.md"
HANDOFFS_DIR = REPO / "docs/handoffs"
DECISION_LINE_RE = re.compile(r"^- \*\*(\d{4}-\d{2}-\d{2})\*\* — (.+)$")


def git(*args: str) -> str | None:
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), *args], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def gh(*args: str) -> str | None:
    if not shutil.which("gh"):
        return None
    try:
        return subprocess.run(
            ["gh", *args], capture_output=True, text=True, check=True, timeout=20,
            cwd=str(REPO),
        ).stdout.strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None


def rule(title: str) -> None:
    print(f"\n{'─' * 72}\n{title}\n{'─' * 72}")


def days_since(datestr: str, today: dt.date) -> int:
    return (today - dt.date.fromisoformat(datestr)).days


def current_pr_ci(branch: str | None) -> tuple[str, list[str]]:
    """Return a precise current-branch PR/CI summary without turning absence into green."""
    if not branch or not shutil.which("gh"):
        return "NOT CHECKED", ["gh CLI unavailable, or branch unknown"]
    raw = gh("pr", "list", "--state", "open", "--head", branch, "--limit", "1",
             "--json", "number")
    if raw is None:
        return "NOT CHECKED", ["GitHub query failed or authentication is unavailable"]
    try:
        rows = json.loads(raw)
    except json.JSONDecodeError:
        return "NOT CHECKED", ["GitHub returned unreadable PR data"]
    if not rows:
        return "NO OPEN PR", ["CI status is not applicable to an open PR on this branch"]
    number = str(rows[0]["number"])
    checks_raw = gh("pr", "view", number, "--json", "statusCheckRollup")
    if checks_raw is None:
        return f"PR #{number} · NOT CHECKED", ["status checks query failed"]
    try:
        checks = json.loads(checks_raw).get("statusCheckRollup") or []
    except json.JSONDecodeError:
        return f"PR #{number} · NOT CHECKED", ["status checks payload unreadable"]
    if not checks:
        return f"PR #{number} · NO CHECKS", ["no status checks are reported"]
    details: list[str] = []
    bad = False
    pending = False
    for item in checks:
        name = item.get("name") or item.get("context") or item.get("workflowName") or "check"
        conclusion = item.get("conclusion") or item.get("state") or item.get("status") or "UNKNOWN"
        details.append(f"{name}: {conclusion}")
        upper = str(conclusion).upper()
        if upper in {"FAILURE", "ERROR", "CANCELLED", "TIMED_OUT", "ACTION_REQUIRED"}:
            bad = True
        elif upper not in {"SUCCESS", "NEUTRAL", "SKIPPED"}:
            pending = True
    verdict = "FAIL" if bad else "PENDING" if pending else "GREEN"
    return f"PR #{number} · {verdict}", details


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--decisions", type=int, default=6,
                    help="how many recent decisions to print (default 6)")
    args = ap.parse_args()

    today = dt.datetime.now(dt.timezone.utc).date()
    print(f"SESSION BRIEF — {today.isoformat()} (UTC), generated by scripts/session_brief.py")

    rule("REPOSITORY")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    print(f"  branch          {branch or '(unknown)'}")
    default_ref = next(
        (r for r in DEFAULT_BRANCH_CANDIDATES
         if git("rev-parse", "--verify", "--quiet", r) is not None), None
    )
    if default_ref:
        tip = git("log", "-1", "--format=%h %ad %s", "--date=short", default_ref)
        print(f"  {default_ref:<15} {tip}")
        counts = git("rev-list", "--left-right", "--count", f"{default_ref}...HEAD")
        if counts:
            behind, ahead = counts.split()
            print(f"  vs default      {ahead} ahead · {behind} behind")
    else:
        print("  default branch  NOT FOUND — no origin/main|master|maintenance")

    dirty = git("status", "--porcelain")
    if dirty is None:
        print("  working tree    UNKNOWN (git unavailable)")
    elif dirty:
        print(f"  working tree    ⚠ DIRTY — {len(dirty.splitlines())} uncommitted path(s)")
    else:
        print("  working tree    clean")

    migrations = sorted(
        p for p in REPO.glob(f"**/{MIGRATIONS_DIR_MARKER}/*.py") if p.name != "__init__.py"
    )
    if migrations:
        print(f"  migration head  {migrations[-1].name} ({len(migrations)} total)")

    rule("GITHUB / CI")
    prs = gh("pr", "list", "--state", "open", "--limit", "20", "--json",
             "number,title,isDraft", "--template",
             '{{range .}}  #{{.number}}{{if .isDraft}} (draft){{end}} {{.title}}\n{{end}}')
    if prs is None:
        print("  open PRs        NOT CHECKED — gh unavailable, unauthenticated, or query failed")
    elif not prs.strip():
        print("  open PRs        none")
    else:
        print("  open PRs")
        print(prs.rstrip())
    ci_summary, ci_details = current_pr_ci(branch)
    print(f"  current branch  {ci_summary}")
    for detail in ci_details:
        print(f"                  {detail}")

    rule(f"RECENT DECISIONS (newest {args.decisions})")
    if not DECISIONS_MD.exists():
        print(f"  {DECISIONS_MD.relative_to(REPO)} MISSING")
    else:
        shown = 0
        for line in DECISIONS_MD.read_text(encoding="utf-8").splitlines():
            match = DECISION_LINE_RE.match(line)
            if not match:
                continue
            date, rest = match.groups()
            headline = re.sub(r"\*\*(.+?)\*\*", r"\1", rest)
            headline = re.sub(r"\s+", " ", headline).strip()
            if len(headline) > 150:
                headline = headline[:147] + "..."
            print(f"  {date} ({days_since(date, today):>3}d)  {headline}")
            shown += 1
            if shown >= args.decisions:
                break
        if shown == 0:
            print("  no entries yet — start with your next real decision")
        print(f"\n  full log: {DECISIONS_MD.relative_to(REPO)}")

    rule("STATE FRESHNESS")
    if not STATE_MD.exists():
        print(f"  {STATE_MD.relative_to(REPO)} MISSING")
    else:
        text = STATE_MD.read_text(encoding="utf-8")
        records = all_freshness(text, today, SECTION_TTLS, WORKSTREAM_TTL)
        if not records:
            print("  no freshness-controlled sections or workstream rows found")
        for record in records:
            label = record.name if record.source == "section" else f"workstream:{record.name}"
            if record.stamp is None or record.age_days is None:
                print(f"  {label:<30} ⚠ NO VALID as-of ({record.ttl_days}d TTL)")
                continue
            verdict = "STALE" if record.age_days > record.ttl_days else "ok"
            mark = "⚠" if verdict == "STALE" else " "
            print(
                f"  {label:<30} {mark} {verdict:<5} as-of {record.stamp} "
                f"({record.age_days}d, TTL {record.ttl_days}d)"
            )
        size_kb = len(text.encode("utf-8")) / 1024
        longest = max((len(line) for line in text.splitlines()), default=0)
        print(f"  size                           {size_kb:.1f} KB · longest line {longest} chars")

    rule("NEWEST HANDOFFS")
    if not HANDOFFS_DIR.exists():
        print(f"  {HANDOFFS_DIR.relative_to(REPO)} MISSING")
    else:
        files = sorted(
            (p for p in HANDOFFS_DIR.glob("*.md") if p.name not in {"INDEX.md", "TEMPLATE.md"}),
            reverse=True,
        )[:5]
        if not files:
            print("  none yet")
        for path in files:
            print(f"  {path.relative_to(REPO)}")

    rule("NOT COVERED BY THIS BRIEF")
    print("  · Deployed revision and live configuration — verify on the host.")
    print("  · Anything in docs/archive/ — read-only, never current.")
    print(f"  · Intent: open {STATE_MD.relative_to(REPO)} §NOW and §NEXT before starting.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
